apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::911804016264:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-US9M5FGWN9LF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::911804016264:role/UdacityFlaskDeployCBKubectlRole
      username: build   
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-08T07:28:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1609"
  uid: 9d772d84-1d3a-48d3-b40b-c7221acefe46
