apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::175450128680:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-TNXZQVTZAPG9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::175450128680:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-29T18:48:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1520"
  uid: 5c15b2ea-25e0-4408-9675-3012a2c67cc8
